services:

  mocks:
    build:
      context: .
      dockerfile: Dockerfile.mocks

    expose:
      - 3000

  test:
    build:
      context: .
      dockerfile: Dockerfile.test

    depends_on:
      - mocks

    environment:
      APP_ENV: test
      IS_TEST: 'true'
      LOG_LEVEL: error
      GITHUB_BASE_URL: http://mocks:3000/github
